# Generated by Django 5.2.4 on 2026-07-07

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_identificador', models.CharField(default='serie', max_length=30)),
                ('prefix', models.CharField(max_length=100)),
                ('numero_parte', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('firma_json', models.JSONField(blank=True, default=dict)),
                ('firma_texto', models.TextField(blank=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('min_required', models.PositiveIntegerField(default=3)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('campo_identificador', 'prefix'),
            },
        ),
        migrations.AddIndex(
            model_name='patronserie',
            index=models.Index(fields=['activo', 'campo_identificador', 'prefix'], name='conceptos_patron_lookup_idx'),
        ),
    ]
