# Generated by Django 5.2.4 on 2026-07-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0002_patronserie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCoincidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('numero_parte', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('firma_texto', models.TextField(blank=True)),
                ('firma_json', models.JSONField(blank=True, default=dict)),
                ('regla_usada', models.CharField(default='manual', max_length=50)),
                ('match_type', models.CharField(default='confirmado', max_length=50)),
                ('confirmado_en_importacion', models.BooleanField(default=False)),
                ('usar_para_biblioteca', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conceptos.concepto')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conceptos.documentoconceptos')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
