# Generated by Django 5.2.4 on 2026-07-11

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0003_historialcoincidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaPatronSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('numero_parte', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('firma_json', models.JSONField(blank=True, default=dict)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('conflicto', 'Conflicto')], default='pendiente', max_length=20)),
                ('motivo_conflicto', models.TextField(blank=True)),
                ('source', models.CharField(default='historial_coincidencia', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
