# Generated by Django 6.0.6 on 2026-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProductoServicioSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('incluir_iva_trasladado', models.CharField(blank=True, max_length=100)),
                ('incluir_ieps_trasladado', models.CharField(blank=True, max_length=100)),
                ('complemento_que_debe_incluir', models.TextField(blank=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('estimulo_franja_fronteriza', models.CharField(blank=True, max_length=50)),
                ('palabras_similares', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fraccion', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
