# Generated by Django 6.0.6 on 2026-06-30 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_catalogo', models.CharField(choices=[('numeros_parte', 'Numeros de parte'), ('sat_clave_producto_servicio', 'SAT clave producto/servicio')], max_length=50)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('total_procesadas', models.PositiveIntegerField(default=0)),
                ('total_creadas', models.PositiveIntegerField(default=0)),
                ('total_actualizadas', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('con_errores', 'Con errores'), ('fallida', 'Fallida')], max_length=30)),
                ('errores_resumen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
