# Generated by Django 6.0.6 on 2026-06-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cargacatalogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargacatalogo',
            options={'permissions': [('puede_ver_historial_cargas_catalogo', 'Puede ver historial de cargas de catalogo')]},
        ),
        migrations.AlterModelOptions(
            name='claveproductoserviciosat',
            options={'permissions': [('puede_importar_claves_sat', 'Puede importar claves SAT')]},
        ),
        migrations.AlterModelOptions(
            name='numeroparte',
            options={'permissions': [('puede_importar_numeroparte', 'Puede importar numeros de parte')]},
        ),
    ]
