# Generated by Django 5.2.8 on 2026-06-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='servidor-local', max_length=120)),
                ('app_version', models.CharField(default='0.1.0', max_length=30)),
                ('git_commit', models.CharField(blank=True, max_length=50)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_status', models.CharField(blank=True, max_length=50)),
                ('last_backup_path', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
